# Generated by Django 2.2.19 on 2022-07-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220707_2136'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='uniq_name-measure_unit_pair',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='measure_unit',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='ingredientvolume',
            old_name='volume',
            new_name='amount',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='uniq_name-measurement_unit_pair'),
        ),
    ]
